### ISSUE TITLE
Ergänzung Reflexion der Softwaregruppe

### ISSUE THREAD

**Issue by GAlexMES** [haloshat/Apollo13_Documentation#10]
Unter 7. Reflexion des Projektverlaufes fehlt die Reflexion der Softwaregruppe

**Comment by mhuisi** [comment]
Fertiggestellt

**Comment by mhuisi** [comment]
Reflexion für die Android-Applikation fehlt noch

**Comment by GAlexMES** [comment]
AppReflexion eingefügt in 28d8ceb4d01add68012d7943c446cef9e2bc729f
daher -> close!
