### ISSUE TITLE
Software -Manuelle Tests

### ISSUE THREAD

**Issue by GAlexMES** [haloshat/Apollo13_Documentation#11]
Text ergänzen oder Punkt entfernen. Zu finden [hier](https://github.com/haloshat/Apollo13_Documentation/blob/31eed9e4ae5aa45515d8ed47c7990cf5b404e9b0/3_Beschreibung_der_Bodenstation/bodenstation_doku_softwaretests.tex#l5)!!

**Comment by RobinBley** [comment]
Erledigt
