### ISSUE TITLE
Fehlende Werte in Anforderungen ergänzen

### ISSUE THREAD

**Issue by mhuisi** [haloshat/Apollo13_Documentation#13]
Es fehlen noch Werte in den Anforderungen.
"Planmäßige Flugzeit" und "Länge des Bergungssystem" sollten noch ergänzt werden.

**Comment by mhuisi** [comment]
Falls nicht ergänzbar: Bitte genauer erläutern wann diese Werte ergänzt werden

**Comment by amazinq** [comment]
"Länge des Bergungssystems" geaddet Flugzeit bisher nicht bekannt muss noch ergänzt werden

**Comment by ghost** [comment]
Flugzeit ist unbekannt und bleibt unbekannt!
