### ISSUE TITLE
Aufgetretene Probleme erweitern

### ISSUE THREAD

**Issue by mhuisi** [haloshat/Apollo13_Documentation#19]
Den Bereich Aufgetretene Probleme mit allen neuen Problemen erweitern.

**Comment by amazinq** [comment]
probleme mit der spannungsversorgung des transceivermoduls sind drin... wir sollten allerdings noch was zur unterbringung der batterie bzw. des schalters schreiben, den wir ja noch nichtmal haben :s

**Comment by mhuisi** [comment]
Scheint fertig zu sein.
