### ISSUE TITLE
Ergänzung Zeitplan Softwaregruppe

### ISSUE THREAD

**Issue by GAlexMES** [haloshat/Apollo13_Documentation#3]
Die Softwaregruppe müsste unter:
4. Projektplanung (3-4 Seiten)
    i. Zeitplan der CanSat Vorbereitung

Bitte einen Text für die Zeitplanung der Softwaregruppe erstellen und zusätzlich ein verwendbares gantt Diagramm in den anhang packen.

**Comment by GAlexMES** [comment]
Gantt wurde erstellt und eingebunden
Erklärende Text fehlt
Gantt und Text der Android Applikation fehlt

**Comment by mhuisi** [comment]
Erklärender Text der Bodenstation ist fertig.

**Comment by GAlexMES** [comment]
Android Gantt hinzugefügt mit f5945ff3fbdaab175dc74fde73e94d37183d6014
daher -> close
