### ISSUE TITLE
Korrigieren des Anhang-Floatings

### ISSUE THREAD

**Issue by mhuisi** [haloshat/Apollo13_Documentation#5]
Die Anhänge floaten momentan noch komplett falsch, zusätzlich ist die Überschrift von "Hardware-GANTT" doppelt.

**Comment by GAlexMES** [comment]
Hardware-GANTT doppelt liegt daran, dass als pagecommand "\subsection{} beim includepdf als parameter übergeben wird.

**Comment by GAlexMES** [comment]
Das Floating liegt ebenfalls an dem includepdf. Vorschlag meinerseits: statt die GANTTs als PDF einzubinden binde ich sie nun als PNG ein
