### ISSUE TITLE
Probleme der Hardware Gruppe

### ISSUE THREAD

**Issue by GAlexMES** [haloshat/Apollo13_Documentation#6]
Unter Beschreibung des CANSAT (10 Seiten) -> Aufgetretene Probleme müssen die Probleme der Hardware ergänzt werden. Teilweise sind Punkte vorhanden, jedoch fehlt noch der Text.

**Comment by amazinq** [comment]
Einige Dinge geadded: siehe a6371d0c06974f2eb4399a6a477e9de66f0ef01d
Der Rest muss von Till erledigt werden.

**Comment by GAlexMES** [comment]
Unbedingt UART I2C-Bus ergänzen

**Comment by ghost** [comment]
UART, I²C ergänzt.
